### ISSUE TITLE
code Polish tracking issue

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/LuxurySparse.jl#7]
- [x] some place like this only need one `@inbounds`, not a big problem though
- [x] benchmark

https://github.com/QuantumBFS/LuxurySparse.jl/blob/e9d48b9434936d57604ce7b12bce3eb1b1f213c5/src/kronecker.jl#L19

- [x] Use `view` or use `view` when this is larger than a threshold.
- [x] benchmark

https://github.com/QuantumBFS/LuxurySparse.jl/blob/e9d48b9434936d57604ce7b12bce3eb1b1f213c5/src/kronecker.jl#L54

- [ ] LLVM could have bad performance here,  for nested loop.
- [ ] benchmark

https://github.com/QuantumBFS/LuxurySparse.jl/blob/e9d48b9434936d57604ce7b12bce3eb1b1f213c5/src/kronecker.jl#L72

- [x] this could cause failure on SIMD
- [x] benchmark

https://github.com/QuantumBFS/LuxurySparse.jl/blob/e9d48b9434936d57604ce7b12bce3eb1b1f213c5/src/kronecker.jl#L208
